export const ActionTypes = {
    SIGN_IN: "SIGN_IN",
    SIGN_UP: "SIGN_UP",
    ADD_EMPPLOYEE: "ADD_EMPPLOYEE",
    REMOVE_EMPLOYEE: "REMOVE_EMPLOYEE",
    VIEW_EMPLOYEE: "VIEW_EMPLOYEE",
    ACTIVE: "ACTIVE",
    INACTIVE: "ACTIVE"
}